apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "demo-gcb-3"
  links:
    - title: Production
      url: https://demo-gcb-3.glair.id
    - title: Staging
      url: https://demo-gcb-3-staging.glair.id
    - title: Develop
      url: https://demo-gcb-3-develop.glair.id
  annotations:
    google.com/cloudbuild-project-slug: 'intern-infra'
    google.com/cloudbuild-repo-name: rey-gdp-intern/demo-gcb-3
    google.com/cloudbuild-location: 'asia-east1'
spec:
  type: service
  owner: group:sre
  lifecycle: experimental